# Generated by Django 5.2.4 on 2025-07-24 14:29

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbu', models.CharField(max_length=100)),
                ('reviewer_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2)),
                ('hr_email_list', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('reviewers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SBU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_og', models.TextField()),
                ('password_hash', models.TextField()),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('REVIEWER', 'Reviewer'), ('HR', 'HR'), ('ADMIN', 'Admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('department', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('is_hr', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('candidate_type', models.CharField(choices=[('INTERN', 'Internship'), ('FULL_TIME', 'Full Time')], max_length=20)),
                ('cv_url', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('current_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('REJECTED', 'Rejected'), ('CONSIDERED', 'To Be Considered'), ('IN_PROCESS', 'In Process'), ('FINAL_ACCEPTED', 'Final Accepted'), ('FINAL_REJECTED', 'Final Rejected')], default='PENDING_REVIEW', max_length=30)),
                ('additional_comment', models.TextField(blank=True, null=True)),
                ('sbus', models.ManyToManyField(to='api.sbu')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('REJECTED', 'Rejected'), ('CONSIDERED', 'To Be Considered')], max_length=20)),
                ('comment', models.TextField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.referral')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='HREvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('TEST', 'Test'), ('T1', 'Technical Round 1'), ('T2', 'Technical Round 2'), ('T3', 'Technical Round 3'), ('HR', 'HR Round'), ('OTHER', 'Other Reason')], max_length=20)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=20)),
                ('comment', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.referral')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_updates', to='api.user')),
            ],
        ),
    ]
