# Generated by Django 5.2.4 on 2025-07-24 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(db_column='referrer_emp_id', on_delete=django.db.models.deletion.CASCADE, to='api.user', to_field='emp_id'),
        ),
    ]
