# Generated by Django 4.2.10 on 2025-07-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_referral_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='rejection_stage',
            field=models.CharField(blank=True, choices=[('SBU', 'SBU'), ('HR', 'HR')], max_length=10, null=True),
        ),
    ]
