# Generated by Django 4.2.10 on 2025-07-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_referral_rejection_reason_referral_rejection_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbu',
            name='departments',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='sbu',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
