# Generated by Django 4.2.10 on 2025-07-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sbu_departments_alter_sbu_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='current_status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('REJECTED', 'Rejected'), ('CONSIDERED', 'To Be Considered'), ('FINAL_ACCEPTED', 'Final Accepted'), ('FINAL_REJECTED', 'Final Rejected')], default='PENDING_REVIEW', max_length=30),
        ),
    ]
