# Generated by Django 4.2.10 on 2025-07-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='purpose',
            field=models.CharField(choices=[('CV_TO_SBU', 'CV Referral (to SBU)'), ('CV_APPROVED_SBU', 'CV Referral Approved [By SBU]'), ('CV_REJECTED_SBU', 'CV Referral Disapproved [By SBU]'), ('CV_TO_HR', 'CV Referral to HR'), ('CV_APPROVED_HR', 'CV Referral Approved [By HR]'), ('CV_REJECTED_HR', 'CV Referral Disapproved [By HR]'), ('CV_UPDATED_SBU', 'CV Referral Updated [To SBU]'), ('CV_DELETED_SBU', 'CV Referral Deleted [To SBU]')], max_length=50, unique=True),
        ),
    ]
