# Generated by Django 4.2.10 on 2025-07-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_emailtemplate_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='purpose',
            field=models.CharField(choices=[('CV_TO_SBU', 'CV Referral (to SBU)'), ('CV_APPROVED_SBU', 'CV Referral Approved [By SBU]'), ('CV_REJECTED_SBU', 'CV Referral Disapproved [By SBU]'), ('CV_TO_HR', 'CV Referral to HR'), ('CV_APPROVED_HR', 'CV Referral Approved [By HR]'), ('CV_REJECTED_HR', 'CV Referral Disapproved [By HR]'), ('CV_UPDATED_SBU', 'CV Referral Updated [To SBU]'), ('CV_DELETED_SBU', 'CV Referral Deleted [To SBU]'), ('CV_APPROVED_SBU_REFERRER', 'CV Approved by SBU - Notify Referrer'), ('CV_APPROVED_SBU_TO_HR', 'CV Approved by SBU - Notify HR'), ('CV_REVOKED_BY_SBU', 'CV Approval Revoked by SBU - Notify HR')], max_length=50, unique=True),
        ),
    ]
