# Generated by Django 4.2.10 on 2025-07-31 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_emailtemplate_purpose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sbu',
            old_name='departments',
            new_name='department',
        ),
    ]
