# Generated by Django 4.2.10 on 2025-07-31 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_departments_sbu_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sbu',
            old_name='department',
            new_name='departments',
        ),
    ]
