# Generated by Django 4.2.10 on 2025-08-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_personal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbu',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
