# Generated by Django 4.2.10 on 2025-10-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sbu_personal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_reason_type',
            field=models.CharField(choices=[('PERSONAL_CONNECTION', 'Personal Connection Referral'), ('TALENT_BASED', 'Referral Based on Talent')], default='PERSONAL_CONNECTION', max_length=30),
        ),
    ]
