# Generated by Django 4.2.10 on 2025-10-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_referral_referral_reason_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='band',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reporting_manager_emp_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reporting_manager_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sub_bu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
