# Generated by Django 4.2.10 on 2025-10-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_jobvacancy_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='appliers_emp_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='review_decision',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
