# Generated by Django 4.2.10 on 2025-10-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_jobapplication_appliers_emp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='review_decision',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
