# Generated by Django 4.2.10 on 2025-10-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_jobapplication_review_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_reason_type',
            field=models.CharField(choices=[('COURTESY', 'Courtesy Referral : Shared out of obligation or goodwill (e.g., customer, family, or acquaintance referral not aligned to any open role).'), ('POTENTIAL_FIT', 'Potential Fit Referral : Candidate with a strong background/skills; evaluation depends on role fitment and mutual interest.'), ('DIRECT_ROLE_FIT', 'Direct Role Fit Referral : Candidate clearly aligned with an existing open position and worth evaluating formally.'), ('INTERNAL_NETWORK', 'Internal Network Referral : Former colleague, vendor contact, or past intern with prior association with Tor or related teams.'), ('STRATEGIC', 'Strategic Referral : High-value or niche skillset candidate referred by leadership or key partner, considered for special review.')], default='COURTESY', max_length=30),
        ),
    ]
